title: James Ireland
description: PhD graduate from the Human Centred Technology Research Centre, University of Canberra, Australia
Email: James.Ireland.PhD@gmail.com 
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: False
